### PR TITLE
local storage impl & hide dark mode toggle on section

### LINKED ISSUE #63: Local storage implementation to save app state on page refresh
@katherinepeterson , as discussed previously , to work on "clearAll"  functionality and other things , local storage should be in place . It's even relevant and meaningful to implement before we implement the "adding a new custom section" functionality . I'll take this up.

### LINKED ISSUE #64: Dark mode toggle button does not hide , when a section is deleted
When a section is disabled , then the editor is also not visible , so we need to hide the dark mode toggle button as well .

image

### PR DESCRIPTION
**Pull request by saurabhchaturvedy**
fixes #63 
fixes #64

### CODE REVIEW

**Comment by saurabhchaturvedy** [comment]
@katherinepeterson i have implemented the local storage functionality . Try it out on the preview deployment url and let me know your thoughts about it and any issues/gaps you face while validating the feature/code . If you think there are issues / we can move this to draft mode , and keep fixing remaining issues . If you think , its good to go , still let me test it on the preview deployment for one more day to be sure its good to go !

Also , this PR also fixes the issue where now when a section is deleted , dark-mode-toggle button also gets hidden , as there is no editor to toggle upon , unless a user selects a section to work upon .

**Comment by katherinepeterson** [comment]
@saurabhchaturvedy looks pretty good, a couple notes:

1. It looks like some of the changes are just formatting. Looks like you either aren't using a formatter or it's using different settings. Could you run Prettier with the settings in `.prettierrc`?
2. Can you resolve the conflicts with main?

**Review by katherinepeterson — CHANGES_REQUESTED** [review]
@saurabhchaturvedy looks pretty good, a couple notes:

It looks like some of the changes are just formatting. Looks like you either aren't using a formatter or it's using different settings. Could you run Prettier with the settings in .prettierrc?
Can you resolve the conflicts with main?

**Comment by saurabhchaturvedy** [comment]
@katherinepeterson , sure will fix the formatting & resolve the conflicts . Thanks for reviewing .

**Comment by rohitjmathew** [comment]
I noticed a bug with respect to the state always having title and description section present even when i delete it. It resets to this. @katherinepeterson can you confirm if this is the behaviour we want?

**Before Refresh:**

Screenshot 2021-04-23 at 1 46 05 PM

**After Refresh**

Screenshot 2021-04-23 at 1 47 31 PM

**Comment by saurabhchaturvedy** [comment]
@rohitjmathew @katherinepeterson  i actually kept it like this , to let user start off with a placeholder every time , as instead of showing empty selected sections (as also when first user clicks the editor page links he starts with 'title-and-description'),  as anyways user will try to select something to start with .  But if thats does not good , i'll change it .

**Comment by saurabhchaturvedy** [comment]
closing this PR as merging changes for two changes clubbed together on PR #80

**Pull request closed without merging**
