### PR TITLE
local storage+ dark mode toggle hide + (Author/Acknowledgements - separate sections)

### LINKED ISSUE #63: Local storage implementation to save app state on page refresh
@katherinepeterson , as discussed previously , to work on "clearAll"  functionality and other things , local storage should be in place . It's even relevant and meaningful to implement before we implement the "adding a new custom section" functionality . I'll take this up.

### LINKED ISSUE #64: Dark mode toggle button does not hide , when a section is deleted
When a section is disabled , then the editor is also not visible , so we need to hide the dark mode toggle button as well .

image

### LINKED ISSUE #66: Suggested change : "Authors" and "Acknowledgement" should be separate sections
@katherinepeterson , i think its better to keep authors and acknowledgement sections as separate , as they kinda serve a bit different purpose , also one unassumed benefit would be that the section name also would not be unnecessary too long which might also avoid bloating UI alignment in future .

**My understanding on purpose of sections** :
Authors -- can be used mention the key authors of the codebase/project
Acknowledgements - also mean crediting other libs , projects , of which help/inspiration was taken to build a project . One such example here :  https://github.com/othneildrew/Best-README-Template

### PR DESCRIPTION
**Pull request by saurabhchaturvedy**
fixes #63 
fixes #64 
fixes #66 

Hi @katherinepeterson 

**1.** This MR fixes the issues raised by you on **Local storage**  previously PR #67 
(i.) Have formatted the code carefully using settings provided in the .prettierrc . Hope it looks good now .
(ii.) I have formatted each and every file which i changed in this PR , so it has just formatted as per settings in .prettierrc file.
(iii.) Included the suggested change from @rohitjmathew  "bug with respect to the state always having title and description section present even when i delete it." Now when you delete all sections , the browser refresh shows empty selected sections , consistent with previous local storage . I have tested some scenarios and looks good from my side .

**2.** This MR fixes the issue  **hide dark mode toggle-button** , when a section is deleted .

**3.** This MR fixes the issue raised by you on **Author/Acknowledgement separate section** fix :
(i.) I have remove the extra ' . ' in the section-columns.js as pointed by in previous PR #74 
(ii.) Have carefully formatted the code using settings in .prettierrc file . Hope its fine now .

Merge status : This PR has no conflict with the base branch . Let me know your comments and please approve PR if looks good .

### CODE REVIEW

**Comment by rohitjmathew** [comment]
@katherinepeterson @saurabhchaturvedy I feel it makes more sense to store the data in session storage than in local storage. We want to ideally keep the data only for the existing session. Opening a page in a new tab should be considered as a feesh instance. Does this make sense to you guys as well?

[Mozilla Session Storage Documentation](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage) to help provide some clarity

**Comment by saurabhchaturvedy** [comment]
@katherinepeterson @rohitjmathew if you have a look at the Swagger Editor (https://editor.swagger.io/) , it is used by backend devs heavily to design OpenAPI standard API specifications for building Microservices . They are also using localStorage .

image

The idea here is usually if an end user closes a tab , he can still start with what he was already working on since localStorage provides us the state . Such approach is usually common across utility editors and is quite simple to comprehend . Although once at-least we merge and onboard this feature and let folks use it, we can think and decide if sessionStorage will add more value in future . Then we can add that feature .

**Comment by saurabhchaturvedy** [comment]
@katherinepeterson i have resolved the merge conflicts again right now & tested scenarios again . Requesting you if we can we go ahead and merge this ? As the other 2 changes (Author/Acknowledge & dark mode toggle hide ) were really small i included them in this PR only . From next time onwards in future , i will definitely ensure PR per issue only be requested from my side . Thanks .

**Comment by katherinepeterson** [comment]
had to fix some conflicts and stuff, will merge these changes from this branch: https://github.com/katherinepeterson/readme.so/pull/92

**Pull request closed without merging**
