### PR TITLE
Add unit tests

### PR DESCRIPTION
**Pull request by annacjy**
Related to: #3 

I've added some unit tests using RTL and Jest, however it doesn't cover 100% of the functionality such as the drag and drop because RTL doesn't provide drag/drop user events. Perhaps we could try implementing e2e test with Cypress for example to cover the drag and drop functionality

### CODE REVIEW

**Review by katherinepeterson — CHANGES_REQUESTED** [review]
The tests looks good, but there is an error when deploying:

image

**Comment by annacjy** [comment]
Hi @katherinepeterson, I found the reason why the build was failing. https://stackoverflow.com/questions/57838908/build-error-occurred-referenceerror-describe-is-not-defined-during-now-sh-dep. I will implement a better solution instead of moving the `__tests__` folder out of the pages folder.

there's some additional changes to the components that's also making the tests fail, which I will fix in the next commit.

**Comment by alexfertel** [comment]
Hello! This is a wonderful project! I want to help with testing.😁

I wanted to give some feedback, and I hope it's ok to do it here.

---

I think `data-testid` should be used as sparingly as possible since it doesn't follow the guiding principles of RTL. The [official docs](https://testing-library.com/docs/queries/bytestid/#api) explain why just above the `Options` header.

For example, we would rather use the second query, which has the same result:

```js
screen.getByTestId('preview-button')
screen.getByRole('button', { name: /preview/i })
``` 

The second query has three main advantages:

* It removes the need for `data-testid`.
* It resembles the way users use the app, which gives you confidence.
* It builds on accessibility features, so it 'forces' you to make your app more accessible.

---

I think [user-event](https://github.com/testing-library/user-event) is a better alternative to `fireEvent`.

---

I hope this makes sense! Let me know if I can help you with coding.

**Comment by annacjy** [comment]
> Hello! This is a wonderful project! I want to help with testing.😁
> 
> I wanted to give some feedback, and I hope it's ok to do it here.
> 
> I think `data-testid` should be used as sparingly as possible since it doesn't follow the guiding principles of RTL. The [official docs](https://testing-library.com/docs/queries/bytestid/#api) explain why just above the `Options` header.
> 
> For example, we would rather use the second query, which has the same result:
> 
> ```js
> screen.getByTestId('preview-button')
> screen.getByRole('button', { name: /preview/i })
> ```
> 
> The second query has three main advantages:
> 
> * It removes the need for `data-testid`.
> * It resembles the way users use the app, which gives you confidence.
> * It builds on accessibility features, so it 'forces' you to make your app more accessible.
> 
> I think [user-event](https://github.com/testing-library/user-event) is a better alternative to `fireEvent`.
> 
> I hope this makes sense! Let me know if I can help you with coding.

Yes it definitely makes sense. I was thinking of using `data-testid` as this was a convention to unit testing in general (not RTL principle). I'm not all that familiar with RTL so I'm glad you pointed this out. 

Anyway, since the new changes have the translations in place I could redo it with your suggestion 😄  Thanks!

**Comment by annacjy** [comment]
Hi @katherinepeterson, the build is successful now and I've **_FINALLY_** resolved the merge conflicts and fixed the tests due to the changes. 

I think it would be best to **merge this PR** before any other PRs involving the components as the tests may fail and need changes again. Also, I would suggest to add unit tests as each feature comes along to maintain coverage and it's good TDD practice 🙂 

p/s: Thanks @alexfertel for the feedback! I now realise after implementing your suggestion, that it's definitely better to not use `data-testid` and also found a couple elements without accessibility in place and managed to detect that as well 😉

**Review by katherinepeterson — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
