### PR TITLE
Update Nav.js to vertically align elements

### LINKED ISSUE #116: Readme.so icon and Language item alignment
I've noticed that the readme.so icon and the Language item on the front page are not quite aligned. I'd be happy to help and fix this.

Screenshot 2021-04-29 at 08 36 48

### PR DESCRIPTION
**Pull request by lauracabtay**
The PR fixes #116

### CODE REVIEW

**Comment by lauracabtay** [comment]
As per the issue raised, I aligned the icon / readme.so element in the nav bar with the Language item.

**Comment by MicahBCode** [comment]
To improve the PR don't forget to link the issue following the instructions on here: https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

This PR closes #116

**Comment by lauracabtay** [comment]
Hey there, I've just updated it :)

**Review by katherinepeterson — APPROVED** [review]
Great, thank you!

**Pull request merged**
