### PR TITLE
Add light/dark theme toggle to editor #29

### PR DESCRIPTION
**Pull request by saurabhchaturvedy**
This PR adds the toggle button for switching between light and dark mode for the readme editor .  #29 

image

image

### CODE REVIEW

**Comment by saurabhchaturvedy** [comment]
Feature in action at the deployment url here :  https://readme-so-g2g3hwpt0-katherinepeterson.vercel.app/editor
https://user-images.githubusercontent.com/56601821/114541571-8798a780-9c74-11eb-894c-315abc7e5139.mov

**Comment by jai-dewani** [comment]
As a 3rd person in this, my personal preference will be to have it on the right side with a certain background to hint that it's a button like this 
image

or in the bottom right corner as most platforms have it. 

also maybe add `vertical-align:bottom` to have to align properly with the text. These are just my preferences/suggestion, the last say will of the owner when she reviews the PR

**Comment by saurabhchaturvedy** [comment]
@jai-dewani  thanks for the good suggestions reg background & placement as being a backend dev would need help there to point out tips & issues. I would love to change the placement for it as per whatever we decide collectively .

**Comment by saurabhchaturvedy** [comment]
Adding on top of what you suggested @jai-dewani , tried something in F12 test mode that stays on top-right of my editor instance , and also thought of keeping background and color scheme in line with the website theme .  @katherinepeterson  @jai-dewani Let me know what are your thoughts , and if looks intuitive to the user .

image

image

**Comment by katherinepeterson** [comment]
@saurabhchaturvedi234 @jai-dewani good thoughts here, my preference would be to have it in the top right of the editor like your last screenshot, but you can keep the original color scheme (the yellow for the sun and gray for the moon)

**Comment by katherinepeterson** [comment]
@saurabhchaturvedy the code looks great btw, so if you just update the placement of the icon I'll merge!

**Comment by jai-dewani** [comment]
and I think some merge conflicts have arisen because #36 was just now closed, so just update the branch with the upstream once

**Comment by saurabhchaturvedy** [comment]
Thanks @katherinepeterson , i have done the alignment update , along with that changed layout of a button like a bar to make it more prominent + box-shadow + little mix of transition effects + few minute color changes .  @jai-dewani  yes updated the forked branch to pull your change . Please verify if its good to merge . Thanks

**Comment by saurabhchaturvedy** [comment]
https://user-images.githubusercontent.com/56601821/114612783-2dbdcf00-9cc0-11eb-84d1-7766abbabf8c.mov

**Comment by katherinepeterson** [comment]
@saurabhchaturvedy I tested it on Safari, and it seems like the button isn't rendering correctly. Btw, there are deploy previews on PRs so I can just look at that instead of videos 

https://readme-so-mnabhxs7r-katherinepeterson.vercel.app/editor

image

**Comment by saurabhchaturvedy** [comment]
@katherinepeterson, i could replicate the safari issue (Working fine with Chrome,IE Edge) . Will check the fix for same and will update here  . And yes will avoid putting in the videos as i agree deploy previews pretty much serve that purpose . Thanks .

**Comment by saurabhchaturvedy** [comment]
@katherinepeterson keeping it simple for now with just the placement update along with keeping the original color scheme (the yellow for the sun and gray for the moon) with as safari have some issue with container-css setting (width: fit-content)& not able to render it properly as its getting overridden . tested with safari,chrome, edge .

**Comment by katherinepeterson** [comment]
@saurabhchaturvedy looks great, thanks so much! Merged!

**Pull request merged**
