### PR TITLE
Fix: screen width

### PR DESCRIPTION
**Pull request by dnmanor**
Hey @katherinepeterson, This should fix the screen width issue. Unfortunately i do not know how to link PRs with Issues so kindly help me out. Ive made another one on the Emoji Issue as well. Thank you.

Closes https://github.com/katherinepeterson/readme.so/issues/91

### CODE REVIEW

**Comment by MicahBCode** [comment]
To link the issue follow the instructions on here: https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

Maybe you can edit your first comment adding the link?

**Comment by dnmanor** [comment]
Thank you for the resources and help. @MicahBCode

**Comment by MicahBCode** [comment]
On the issue linking you could also use a keyword like "closes" in front of the issues id so it's linked and not just mentioned in here.

**Comment by dnmanor** [comment]
Oh okay.

**Comment by MicahBCode** [comment]
> Oh okay.

And with that being. The liked issue will automatically be closed up on merge which is pretty handy. Looks great now! 👍

**Comment by katherinepeterson** [comment]
@dnmanor sorry that I didn't catch this issue, but the min-width was intentional because the editor gets basically unusable once it is squished down to a certain size. However, I do agree that it could shrink more than it currently does, so I think the fix is to keep the min-width but just have it be smaller. I'll take care of making that change.

**Pull request closed without merging**
