### PR TITLE
added shortcut support for KeyE to focus on editor

### LINKED ISSUE #57: Add "e" button shortcut to focus editor

### PR DESCRIPTION
**Pull request by MicahBCode**
The PR adds shortcut support for "e" to focus on editor.

This commit closes #57

### CODE REVIEW

**Comment by katherinepeterson** [comment]
@MicahBCode it looks like this got rid of the ability to tab through all the other buttons on the screen. Can you look into this please?

**Review by katherinepeterson — CHANGES_REQUESTED** [review]
@MicahBCode it looks like this got rid of the ability to tab through all the other buttons on the screen. Can you look into this please?

**Comment by MicahBCode** [comment]
@katherinepeterson Solved the issue. Thanks for reviewing :)

**Comment by katherinepeterson** [comment]
@MicahBCode thank you! Looks great! Do you mind resolving the conflicts, then I will merge?

**Comment by MicahBCode** [comment]
@katherinepeterson Conflicts are resolved now. 👍

**Pull request merged**
