### PR TITLE
Add i18n support to readme.so

### LINKED ISSUE #30: Adding support for i18n
I saw that we should be able to add support to i18n with the following [dependency](https://github.com/isaachinman/next-i18next). Thoughts on adding this to the site?

### PR DESCRIPTION
**Pull request by rohitjmathew**
This PR adds i18n support for English, French and Spanish on the landing page.

This commit closes #30

### CODE REVIEW

**Comment by rohitjmathew** [comment]
@katherinepeterson I have done some initial changes. Would be great if you can review the code and tell me any tips. Would also be great if we can get someone to review the translated text as I used google translate to do this.

**Comment by katherinepeterson** [comment]
@rohitjmathew the code looks nice and clean, I'm going to try to find someone who can proofread these to make sure the translations make sense. 

We will probably want to translate the section headers and templates also if we're going to add this

**Comment by rohitjmathew** [comment]
> @rohitjmathew the code looks nice and clean.

Thanks. Ill try seeing if I can optimise the code a bit more but this was just a quick first attempt. 

>  I'm going to try to find someone who can proofread these to make sure the translations make sense.

Yes please, I used google translation for now and was wondering if we could rope someone in to verify the copy. 

> We will probably want to translate the section headers and templates also if we're going to add this

I had this in mind. Headers make 100% sense. Templates is something they can edit. Do we want that to also be translated?

**Comment by katherinepeterson** [comment]
> Yes please, I used google translation for now and was wondering if we could rope someone in to verify the copy.

I had some friends proofread the translations. They made some suggestions for the Spanish text in this doc:
https://docs.google.com/document/d/1FbQ4bv3jlfgCsq3gR_QkugZXqSXyuTG2W4MEYkbf8KI/edit

> I had this in mind. Headers make 100% sense. Templates is something they can edit. Do we want that to also be translated?

For now let's just do headers!

**Comment by rohitjmathew** [comment]
@katherinepeterson I have added i18n support in most places I can think off. I have also updated the translations for Spanish as provided by you and added a dropdown item incase of incorrect translations (this links to GitHub Issues). 

Do review and see if this is okay? We can merge post that. I can reach out to some people in the Auth0 Ambassador program which @jai-dewani and I are part of and ask for help with translations.

**Comment by jai-dewani** [comment]
I have asked members of EddieHub to check out the preview website if they are Spanish or French speakers and consider reviewing the PR.

**Comment by rohitjmathew** [comment]
@katherinepeterson can we go ahead and merge this code? I have added a section to create a new issue incase of errors in translations.

**Pull request merged**
